CREATE DATABASE db;

CREATE TABLE Pessoa (
    cpf VARCHAR(11),
    email VARCHAR(50) NOT NULL,
    nome VARCHAR(150) NOT NULL,
    data_nasc DATE NOT NULL,
    endereco VARCHAR(300) NOT NULL,
    telefone VARCHAR(15),

    CONSTRAINT pk_pessoa PRIMARY KEY (cpf),
    CONSTRAINT unique_email_nome UNIQUE (email, nome)
);

CREATE TABLE Paciente (
    cpf_pessoa VARCHAR(11),
    senha VARCHAR(20) NOT NULL,
    plano_saude BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT pk_paciente PRIMARY KEY (cpf_pessoa),
    CONSTRAINT fk_cpf_pessoa FOREIGN KEY (cpf_pessoa) REFERENCES Pessoa(cpf) ON DELETE CASCADE
);

CREATE TABLE Medico (
    cpf_pessoa VARCHAR(11),
    crm VARCHAR(10) NOT NULL,

    CONSTRAINT pk_medico PRIMARY KEY (cpf_pessoa),
    CONSTRAINT fk_cpf_pessoa FOREIGN KEY (cpf_pessoa) REFERENCES Pessoa(cpf) ON DELETE CASCADE,
    CONSTRAINT unique_crm UNIQUE (crm)
);

CREATE TABLE Agendamento (
    cpf_paciente VARCHAR(11),
    cpf_medico VARCHAR(11),
    dh_consulta TIMESTAMP,
    dh_agendamento TIMESTAMP NOT NULL,
    valor_consulta FLOAT NOT NULL DEFAULT 0.0,

    CONSTRAINT pk_agendamento PRIMARY KEY (cpf_paciente, cpf_medico, dh_consulta),
    CONSTRAINT fk_cpf_paciente FOREIGN KEY (cpf_paciente) REFERENCES Paciente(cpf_pessoa) ON DELETE CASCADE,
    CONSTRAINT fk_cpf_pessoa FOREIGN KEY (cpf_pessoa) REFERENCES Medico(cpf_pessoa) ON DELETE CASCADE
);

CREATE TABLE Especialidade (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    descricao VARCHAR(300) NOT NULL,

    CONSTRAINT pk_especialidade PRIMARY KEY (id)
);

CREATE TABLE Medico_Especialidade (
    cpf_medico VARCHAR(11),
    id_especialidade INT,

    CONSTRAINT pk_medico_especialidade PRIMARY KEY (cpf_medico, id_especialidade),
    CONSTRAINT fk_cpf_medico FOREIGN KEY (cpf_medico) REFERENCES Medico(cpf_pessoa) ON DELETE CASCADE,
    CONSTRAINT fk_id_especialidade FOREIGN KEY (id_especialidade) REFERENCES Especialidade(id) ON DELETE CASCADE
);