# Generated by Django 5.2.7 on 2025-11-03 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='prioriddade',
            new_name='prioridade',
        ),
    ]
